from django.db import models

class CasForm(models.Model):
    casid = models.AutoField(primary_key=True,db_column='casid')
    Claim_ID = models.CharField(max_length=255,db_column='Claim_ID')
    Insurance = models.CharField(max_length=255,db_column='Insurance')
    Facility = models.CharField(max_length=255,db_column='Facility')
    Charge_From_Date = models.CharField(max_length=20,db_column='Charge_From_Date')
    Charge_To_Date = models.CharField(max_length=20,db_column='Charge_To_Date')
    Facility_NPI = models.CharField(max_length=255,db_column='Facility_NPI')
    Primary_Member_ID = models.CharField(max_length=255,db_column='Primary_Member_ID')
    Charge_Debit_Amount = models.CharField(max_length=20,db_column='Charge_Debit_Amount')
    Pat_Primary_Payer_Name = models.CharField(max_length=255,db_column='Pat_Primary_Payer_Name')
    Patient_Full_Name = models.CharField(max_length=255,db_column='Patient_Full_Name')
    Patient_Birthday = models.CharField(max_length=20,db_column='Patient_Birthday')
    Current_Billing_Status = models.CharField(max_length=255,db_column='Current_Billing_Status')
    Claim_Number = models.CharField(max_length=255,db_column='Claim_Number')
    Patient_Account_Number = models.CharField(max_length=255,db_column='Patient_Account_Number')
    UHC_Availity_ClaimStatus = models.CharField(max_length=255,db_column='UHC_Availity_ClaimStatus')
    Total_BilledAmount = models.CharField(max_length=20,db_column='Total_BilledAmount')
    Total_Paid = models.CharField(max_length=20,db_column='Total_Paid')
    Total_Adjustment = models.CharField(max_length=20,db_column='Total_Adjustment')
    Total_Patient_Responsibility = models.CharField(max_length=20,db_column='Total_Patient_Responsibility')
    Service_Code = models.CharField(max_length=255,db_column='Service_Code')
    Billing_Amount = models.CharField(max_length=20,db_column='Billing_Amount')
    Allowed_Amount = models.CharField(max_length=20,db_column='Allowed_Amount')
    Paid_Amount = models.CharField(max_length=20,db_column='Paid_Amount')
    Check_Number = models.CharField(max_length=255,db_column='Check_Number')
    Check_Date = models.CharField(max_length=20,db_column='Check_Date')
    Remark_Code = models.CharField(max_length=255,db_column='Remark_Code')
    Category_1 = models.CharField(max_length=255,db_column='Category_1')
    Status_1 = models.CharField(max_length=255,db_column='Status_1')
    Description_1 = models.CharField(max_length=255,db_column='Description_1')
    Status_Description_1 = models.CharField(max_length=255,db_column='Status_Description_1')
    Claim_Reason_Code_1 = models.CharField(max_length=255,db_column='Claim_Reason_Code_1')
    Category_2 = models.CharField(max_length=255,db_column='Category_2')
    Status_2 = models.CharField(max_length=255,db_column='Status_2')
    Description_2 = models.CharField(max_length=255,db_column='Description_2')
    Status_Description_2 = models.CharField(max_length=255,db_column='Status_Description_2')
    Claim_Reason_Code_2 = models.CharField(max_length=255,db_column='Claim_Reason_Code_2')
    Category_3 = models.CharField(max_length=255,db_column='Category_3')
    Status_3 = models.CharField(max_length=255,db_column='Status_3')
    Description_3 = models.CharField(max_length=255,db_column='Description_3')
    Status_Description_3 = models.CharField(max_length=255,db_column='Status_Description_3')
    Bot_Status = models.CharField(max_length=255,db_column='Bot_Status')
    Comments = models.CharField(max_length=255,db_column='Comments')
    Updated_By = models.CharField(max_length=255,db_column='Updated_By')
    RCM_Comments = models.CharField(max_length=255,db_column='RCM_Comments')
    cas_assigned_name = models.CharField(max_length=255,db_column='cas_assigned_name')
    cas_status = models.CharField(max_length=20,db_column='cas_status')
    cas_assigned_to = models.CharField(max_length=20,db_column='cas_assigned_to')

    
    class Meta:
            managed = True
            db_table = 'casform'
