# Generated by Django 5.0.1 on 2024-06-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvDetails',
            fields=[
                ('ev_remarks', models.CharField(blank=True, db_column='ev_remarks', max_length=50, null=True)),
                ('ev_status', models.CharField(blank=True, db_column='ev_status', max_length=50, null=True)),
                ('ev_assigned_to', models.CharField(blank=True, db_column='ev_assigned_to', max_length=10, null=True)),
                ('ev_assigned_name', models.CharField(blank=True, db_column='ev_assigned_name', max_length=100, null=True)),
                ('Date_of_service', models.CharField(blank=True, db_column='Date_of_service', max_length=50, null=True)),
                ('patient_name', models.CharField(blank=True, db_column='patient_name', max_length=200, null=True)),
                ('patient_id', models.CharField(blank=True, db_column='patient_id', max_length=100, null=True)),
                ('patient_dob', models.CharField(blank=True, db_column='patient_dob', max_length=50, null=True)),
                ('plan_network', models.CharField(blank=True, db_column='plan_network', max_length=200, null=True)),
                ('subscriber_id', models.CharField(blank=True, db_column='subscriber_id', max_length=100, null=True)),
                ('subscriber_name', models.CharField(blank=True, db_column='subscriber_name', max_length=250, null=True)),
                ('subscriber_dob', models.CharField(blank=True, db_column='subscriber_dob', max_length=50, null=True)),
                ('ev_createddatetime', models.CharField(blank=True, db_column='ev_createddatetime', max_length=100, null=True)),
                ('ev_assigned_createddatetime', models.CharField(blank=True, db_column='ev_assigned_createddatetime', max_length=100, null=True)),
                ('ev_closed_createddatetime', models.CharField(blank=True, db_column='ev_closed_createddatetime', max_length=100, null=True)),
                ('ev_review_created_datetime', models.CharField(blank=True, db_column='ev_review_created_datetime', max_length=100, null=True)),
                ('ev_assigned_timedifference', models.CharField(blank=True, db_column='ev_assigned_timedifference', max_length=50, null=True)),
                ('ev_progress_timedifference', models.CharField(blank=True, db_column='ev_progress_timedifference', max_length=50, null=True)),
                ('ev_id', models.AutoField(db_column='ev_id', primary_key=True, serialize=False)),
            ],
        ),
    ]
