# Generated by Django 5.0.6 on 2024-07-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0003_delete_request_upstreamform_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstreamform',
            name='disclosure_method',
            field=models.CharField(blank=True, db_column='disclosure_method', max_length=255, null=True),
        ),
    ]
