# Generated by Django 5.0.6 on 2024-07-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0005_upstreamform_external_request_createddatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upstreamform',
            name='external_request_createddatetime',
        ),
    ]
