# Generated by Django 5.0.6 on 2024-07-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0007_upstreamform_external_request_createddatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upstreamform',
            name='ev_status',
            field=models.CharField(blank=True, db_column='ev_status', default='New', max_length=50, null=True),
        ),
    ]
