# Generated by Django 5.0.6 on 2024-07-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0009_upstreamform_request_date2'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstreamform',
            name='file_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upstreamform',
            name='file_paths',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
