# Generated by Django 5.0.6 on 2024-07-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0015_upstreamform_misc10_pages_upstreamform_misc10_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upstreamform',
            name='misc10_path',
            field=models.TextField(blank=True, db_column='misc10_path', null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc2_path',
            field=models.TextField(blank=True, db_column='misc2_path', null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc3_path',
            field=models.TextField(blank=True, db_column='misc3_path', null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc4_path',
            field=models.TextField(blank=True, db_column='misc4_path', null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc5_path',
            field=models.TextField(blank=True, db_column='misc5_path', null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc6_path',
            field=models.TextField(blank=True, db_column='misc6_path', null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc7_path',
            field=models.TextField(blank=True, db_column='misc7_path', null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc8_path',
            field=models.TextField(blank=True, db_column='misc8_path', null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc9_path',
            field=models.TextField(blank=True, db_column='misc9_path', null=True),
        ),
    ]
