# Generated by Django 5.0.7 on 2024-08-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0021_alter_upstreamform_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstreamform',
            name='patient_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
