# Generated by Django 5.0.7 on 2024-08-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0023_alter_upstreamform_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upstreamform',
            name='request_id',
            field=models.AutoField(db_column='request_id', primary_key=True, serialize=False),
        ),
    ]
