# Generated by Django 5.0.7 on 2024-08-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0026_alter_upstreamform_ev_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upstreamform',
            name='ev_assigned_to',
            field=models.CharField(blank=True, db_column='ev_assigned_to', max_length=255, null=True),
        ),
    ]
