# Generated by Django 5.1 on 2024-08-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0027_alter_upstreamform_ev_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upstreamform',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='patient_no',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
