# Generated by Django 5.1 on 2024-08-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0029_charginglist'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='charginglist',
            table='charging_lists',
        ),
    ]
