# Generated by Django 5.1 on 2024-08-23 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0033_rename_chargeslist_chargedlist_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chargedlist',
            table='charge_list',
        ),
    ]
