# Generated by Django 5.1 on 2024-08-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0037_charginglist_each_additional_hour_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChargingList',
        ),
    ]
