# Generated by Django 5.1 on 2024-08-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0039_charginglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='charginglist',
            name='minimum_fee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
