# Generated by Django 5.1 on 2024-08-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0040_charginglist_minimum_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='charginglist',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='charginglist',
            name='mail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
