# Generated by Django 5.1 on 2024-09-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0044_alter_requestfile_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestFile',
        ),
    ]
