# Generated by Django 5.0.1 on 2024-06-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_firstname', models.CharField(blank=True, db_column='user_Firstname', max_length=50, null=True)),
                ('user_lastname', models.CharField(blank=True, db_column='user_Lastname', max_length=50, null=True)),
                ('user_mobile', models.CharField(blank=True, db_column='user_Mobile', max_length=20, null=True)),
                ('user_email', models.CharField(blank=True, db_column='user_Email', max_length=100, null=True)),
                ('user_designation', models.CharField(blank=True, db_column='user_Designation', max_length=100, null=True)),
                ('user_company', models.CharField(blank=True, db_column='user_Company', max_length=100, null=True)),
                ('user_SecretKey', models.CharField(blank=True, db_column='user_SecretKey', max_length=255, null=True)),
                ('user_checklist', models.CharField(blank=True, db_column='user_Checklist', max_length=20, null=True)),
                ('user_assign_flag', models.CharField(blank=True, db_column='user_assign_flag', max_length=10, null=True)),
                ('user_username', models.TextField(blank=True, db_column='user_Username', null=True)),
                ('user_password', models.TextField(blank=True, db_column='user_Password', null=True)),
                ('user_createddatetime', models.DateField(blank=True, db_column='user_Createddatetime', null=True)),
                ('user_Type', models.CharField(blank=True, db_column='user_Type', max_length=50, null=True)),
                ('user_id', models.AutoField(db_column='user_ID', primary_key=True, serialize=False)),
            ],
        ),
    ]
