# Generated by Django 5.0.6 on 2024-07-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdetails',
            table='register_userdetails',
        ),
    ]
