# Generated by Django 5.0.6 on 2024-07-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=100)),
                ('patient_last_name', models.CharField(max_length=100)),
                ('patient_date_of_birth', models.DateField()),
                ('requestor_name', models.CharField(max_length=100)),
                ('requestor_email', models.EmailField(max_length=254)),
                ('request_type', models.CharField(max_length=50)),
                ('request_file', models.FileField(upload_to='requests/')),
            ],
        ),
        migrations.RemoveField(
            model_name='upstreamform',
            name='disclosure_method',
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='address1',
            field=models.CharField(blank=True, db_column='address1', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='address2',
            field=models.CharField(blank=True, db_column='address2', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='approve_doc_path',
            field=models.CharField(blank=True, db_column='approve_doc_path', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='approve_doc_status',
            field=models.CharField(blank=True, db_column='approve_doc_status', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='balance',
            field=models.CharField(blank=True, db_column='balance', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='birthdate',
            field=models.CharField(blank=True, db_column='birthdate', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='city',
            field=models.CharField(blank=True, db_column='city', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='close_date',
            field=models.CharField(blank=True, db_column='close_date', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='cng_close_time',
            field=models.CharField(blank=True, db_column='cng_close_time', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='cng_open_time',
            field=models.CharField(blank=True, db_column='cng_open_time', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='company',
            field=models.CharField(blank=True, db_column='company', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='company_no',
            field=models.CharField(blank=True, db_column='company_no', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='copies_due',
            field=models.CharField(blank=True, db_column='copies_due', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='email',
            field=models.CharField(blank=True, db_column='email', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='empl_close',
            field=models.CharField(blank=True, db_column='empl_close', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='empl_open',
            field=models.CharField(blank=True, db_column='empl_open', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='encounter',
            field=models.CharField(blank=True, db_column='encounter', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='ext',
            field=models.CharField(blank=True, db_column='ext', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='fax',
            field=models.CharField(blank=True, db_column='fax', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='fax_number',
            field=models.CharField(blank=True, db_column='fax_number', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='first_name',
            field=models.CharField(blank=True, db_column='first_name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='invoice_no',
            field=models.CharField(blank=True, db_column='invoice_no', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='last_name',
            field=models.CharField(blank=True, db_column='last_name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='med_record_no',
            field=models.CharField(blank=True, db_column='med_record_no', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='medicare',
            field=models.CharField(blank=True, db_column='medicare', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='mi',
            field=models.CharField(blank=True, db_column='mi', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='notes',
            field=models.TextField(blank=True, db_column='notes', null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='optional_info',
            field=models.TextField(blank=True, db_column='optional_info', null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='other_pages',
            field=models.CharField(blank=True, db_column='other_pages', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='paper_copy_pages',
            field=models.CharField(blank=True, db_column='paper_copy_pages', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='phone',
            field=models.CharField(blank=True, db_column='phone', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='purpose',
            field=models.TextField(blank=True, db_column='purpose', null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='request_date',
            field=models.CharField(blank=True, db_column='request_date', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='request_type',
            field=models.CharField(blank=True, db_column='request_type', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='requestor',
            field=models.CharField(blank=True, db_column='requestor', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='ssn',
            field=models.CharField(blank=True, db_column='ssn', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='state',
            field=models.CharField(blank=True, db_column='state', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='status',
            field=models.CharField(blank=True, db_column='status', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='status_date',
            field=models.CharField(blank=True, db_column='status_date', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='suspend',
            field=models.CharField(blank=True, db_column='suspend', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='time',
            field=models.CharField(blank=True, db_column='time', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='time_closed',
            field=models.CharField(blank=True, db_column='time_closed', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='time_opened',
            field=models.CharField(blank=True, db_column='time_opened', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='tpo',
            field=models.CharField(blank=True, db_column='tpo', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='zip_code',
            field=models.CharField(blank=True, db_column='zip_code', max_length=255, null=True),
        ),
    ]
