# Generated by Django 5.0.6 on 2024-07-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0008_alter_upstreamform_ev_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstreamform',
            name='request_date2',
            field=models.CharField(blank=True, db_column='request_date2', max_length=20, null=True),
        ),
    ]
