# Generated by Django 5.0.6 on 2024-07-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0012_upstreamform_total_amount_upstreamform_total_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstreamform',
            name='misc1_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upstreamform',
            name='misc2_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upstreamform',
            name='misc3_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upstreamform',
            name='misc4_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upstreamform',
            name='misc5_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upstreamform',
            name='misc6_pages',
            field=models.IntegerField(default=0),
        ),
    ]
