# Generated by Django 5.0.6 on 2024-07-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0014_alter_upstreamform_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstreamform',
            name='misc10_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upstreamform',
            name='misc10_path',
            field=models.TextField(db_column='misc10_path', default=0),
        ),
        migrations.AddField(
            model_name='upstreamform',
            name='misc7_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upstreamform',
            name='misc7_path',
            field=models.TextField(db_column='misc7_path', default=0),
        ),
        migrations.AddField(
            model_name='upstreamform',
            name='misc8_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upstreamform',
            name='misc8_path',
            field=models.TextField(db_column='misc8_path', default=0),
        ),
        migrations.AddField(
            model_name='upstreamform',
            name='misc9_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upstreamform',
            name='misc9_path',
            field=models.TextField(db_column='misc9_path', default=0),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc1_path',
            field=models.TextField(db_column='misc1_path', default=0),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc2_path',
            field=models.TextField(db_column='misc2_path', default=0),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc3_path',
            field=models.TextField(db_column='misc3_path', default=0),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc4_path',
            field=models.TextField(db_column='misc4_path', default=0),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc5_path',
            field=models.TextField(db_column='misc5_path', default=0),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc6_path',
            field=models.TextField(db_column='misc6_path', default=0),
        ),
    ]
