# Generated by Django 5.0.6 on 2024-07-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0016_alter_upstreamform_misc10_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upstreamform',
            name='misc10_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc1_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc2_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc3_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc4_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc5_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc6_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc7_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc8_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc9_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
