# Generated by Django 5.0.6 on 2024-07-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0017_alter_upstreamform_misc10_pages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upstreamform',
            name='misc10_pages',
        ),
        migrations.RemoveField(
            model_name='upstreamform',
            name='misc10_path',
        ),
        migrations.RemoveField(
            model_name='upstreamform',
            name='misc7_pages',
        ),
        migrations.RemoveField(
            model_name='upstreamform',
            name='misc7_path',
        ),
        migrations.RemoveField(
            model_name='upstreamform',
            name='misc8_pages',
        ),
        migrations.RemoveField(
            model_name='upstreamform',
            name='misc8_path',
        ),
        migrations.RemoveField(
            model_name='upstreamform',
            name='misc9_pages',
        ),
        migrations.RemoveField(
            model_name='upstreamform',
            name='misc9_path',
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc1_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc1_path',
            field=models.TextField(blank=True, db_column='misc1_path', null=True),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc2_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc3_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc4_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc5_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='upstreamform',
            name='misc6_pages',
            field=models.IntegerField(default=0),
        ),
    ]
