# Generated by Django 5.0.6 on 2024-07-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0019_upstreamform_misc10_pages_upstreamform_misc10_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstreamform',
            name='invoice_pdf_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
