# Generated by Django 5.0.7 on 2024-08-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0022_upstreamform_patient_no_alter_upstreamform_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upstreamform',
            name='request_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
