# Generated by Django 5.1 on 2024-08-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0030_alter_charginglist_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChargingList',
            new_name='ChargingLists',
        ),
    ]
