# Generated by Django 5.1 on 2024-08-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0032_chargeslist_delete_charginglists'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChargesList',
            new_name='ChargedList',
        ),
        migrations.AlterModelTable(
            name='chargedlist',
            table='charged_list',
        ),
    ]
