# Generated by Django 5.1 on 2024-08-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0034_alter_chargedlist_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChargedList',
        ),
    ]
