# Generated by Django 5.1 on 2024-09-02 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upstreamform', '0043_requestfile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requestfile',
            table='requestfile',
        ),
    ]
